pull_request_rules:
  - name: automatic merge
    conditions:
      - or:
          - label=dependencies
          - label=automerge
      - check-success=validate
    actions:
      queue:

queue_rules:
  - name: default
    merge_conditions:
      - check-success=validate
    merge_method: rebase
merge_protections_settings:
  reporting_method: check-runs
