pull_request_rules:
  - name: automatic merge dependabot
    conditions:
      - label=dependencies
      - check-success=validate
    actions:
      queue:

queue_rules:
  - name: default
    merge_conditions:
      - check-success=validate
    merge_method: rebase
