"""Compile the ojhunt library documentation into docs/library.md.

Usage: uv run python scripts/generate_library_docs.py  (or ./doit.sh gen-docs)

Everything in the output comes from the live objects — docstrings, signatures and
each crawler's generated help text — so the file is a compiled view of what
help() prints, never a second copy of it. Commit the result.
"""

import inspect
from dataclasses import MISSING, Field, fields
from enum import Enum
from pathlib import Path
from typing import Any, Callable, List

import ojhunt.crawlers
from ojhunt.core.models import (
    CrawlerInfo,
    CrawlerMeta,
    CrawlerRegistry,
    CrawlerResult,
    LoginType,
)
from ojhunt.crawlers import crawlers as crawler_registry
from ojhunt.crawlers import query_sync

REPO_ROOT = Path(__file__).parent.parent
OUTPUT = REPO_ROOT / "docs" / "library.md"

HEADER = """# Python Library Reference

<!-- Generated by scripts/generate_library_docs.py. Run ./doit.sh gen-docs to refresh. -->

OJHunt's crawlers are importable: `ojhunt` ships every online-judge crawler behind
the CLI and the web app as a Python library. This page is compiled from the
docstrings, so the same text is available from a Python prompt via `help()`.

```bash
uv add ojhunt
# or: pip install ojhunt
```
"""

FOOTER_TITLE = "## One crawler in full"


def _block(text: str) -> str:
    """Wrap text in a fenced block that pytest-markdown-docs will not execute."""
    return f"```text\n{text.rstrip()}\n```"


def _doc(obj: Any) -> str:
    """The object's docstring, which this page has nothing to say without."""
    doc = inspect.getdoc(obj)
    assert doc, f"{obj!r} has no docstring to compile"
    return doc


def _readable(annotation: str) -> str:
    """Drop module prefixes that only add noise for a reader."""
    return annotation.replace("typing.", "").replace("ojhunt.core.models.", "")


def _signature(fn: Callable[..., Any]) -> inspect.Signature:
    """Resolve string annotations, so forward refs render without their quotes."""
    return inspect.signature(fn, eval_str=True)


def _function_entry(name: str, fn: Callable[..., Any]) -> str:
    signature = _readable(f"{name}{_signature(fn)}")
    return f"### `{name}()`\n\n" + _block(f"{signature}\n\n{_doc(fn)}")


def _field_line(field: Field) -> str:
    line = f"    {field.name}: {_readable(inspect.formatannotation(field.type))}"
    if field.default is not MISSING:
        default = field.default
        rendered = default.name if isinstance(default, Enum) else repr(default)
        line += f" = {rendered}"
    elif field.default_factory is not MISSING:
        line += f" = {field.default_factory()!r}"
    return line


def _dataclass_entry(cls: type) -> str:
    field_lines = "\n".join(_field_line(f) for f in fields(cls))
    body = f"class {cls.__name__}\n\n{_doc(cls)}\n\nFields\n{field_lines}"
    return f"### `{cls.__name__}`\n\n" + _block(body)


def _class_entry(cls: type) -> str:
    body = f"class {cls.__name__}\n\n{_doc(cls)}"
    return f"### `{cls.__name__}`\n\n" + _block(body)


def _login_type_entry() -> str:
    members = "\n".join(f'    {m.name} = "{m.value}"' for m in LoginType)
    body = f"class LoginType\n\n{_doc(LoginType)}\n\nMembers\n{members}"
    return "### `LoginType`\n\n" + _block(body)


def _extra_arguments(crawler: CrawlerInfo) -> str:
    params = [
        p
        for p in inspect.signature(crawler.query).parameters
        if p not in ("session", "username")
    ]
    return ", ".join(f"`{p}`" for p in params) if params else "–"


def _cell(text: str) -> str:
    """Collapse a metadata string to one line and escape the column separator."""
    return " ".join(text.split()).replace("|", "\\|")


def _crawler_row(crawler: CrawlerInfo) -> str:
    meta: CrawlerMeta = crawler.meta
    title = _cell(meta.title)
    platform = f"[{title}]({meta.url})" if meta.url else title
    login = (
        meta.login_type.label if meta.login_type is not LoginType.NOT_REQUIRED else "–"
    )
    notes = _cell(meta.description) or "–"
    if meta.is_aggregator:
        notes = f"{notes} (aggregator)" if notes != "–" else "Aggregator"
    row = f"| `{crawler.name}` | {platform} | {login} | {notes} | {_extra_arguments(crawler)} |"
    assert row.count("|") - row.count("\\|") == 6, f"malformed table row: {row!r}"
    return row


def render_library_docs() -> str:
    crawlers: List[CrawlerInfo] = [c for _, c in sorted(crawler_registry.items())]
    assert crawlers, "no crawlers discovered — the table and example would be empty"

    sections = [
        HEADER,
        "## Library guide",
        "",
        "Printed by `help(ojhunt.crawlers)`.",
        "",
        _block(_doc(ojhunt.crawlers)),
        "",
        "## API",
        "",
        "Everything below is importable from `ojhunt.crawlers`. The registry itself "
        "is the module attribute `crawlers`, a `CrawlerRegistry` built on first "
        "access.",
        "",
        _class_entry(CrawlerRegistry),
        "",
        _function_entry("query_sync", query_sync),
        "",
        _dataclass_entry(CrawlerResult),
        "",
        _dataclass_entry(CrawlerInfo),
        "",
        "",
        _dataclass_entry(CrawlerMeta),
        "",
        _login_type_entry(),
        "",
        "## Supported crawlers",
        "",
        f"{len(crawlers)} crawlers. Every one takes `(session, username)`; the "
        'arguments below are additional. Run `help(crawlers["<name>"])` for one '
        "crawler's full entry.",
        "",
        "| Crawler | Platform | Login | Username / notes | Extra arguments |",
        "| --- | --- | --- | --- | --- |",
        "\n".join(_crawler_row(c) for c in crawlers),
        "",
        FOOTER_TITLE,
        "",
        "What `help()` gives you for a single crawler, credentials and all.",
        "",
    ]

    example = next(
        (c for c in crawlers if c.meta.login_type is not LoginType.NOT_REQUIRED),
        crawlers[0],
    )
    sections.append(_block(f"{example!r}\n\n{_doc(example)}"))

    return "\n".join(sections).rstrip() + "\n"


def main() -> None:
    OUTPUT.write_text(render_library_docs(), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
